name: ci

on:
  push:
    branches: [ master, develop]
    paths:
      - 'environment.yml'
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Get branch name for later tagging
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      -
        name: Convenience renaming of develop to dev
        if: ${{ env.BRANCH == 'develop' }}
        run: echo "BRANCH=dev" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: .devcontainer/Dockerfile
          push: true
          tags: thllwg/maya-challenge:${{ env.BRANCH }}, thllwg/maya-challenge:latest
          build-args: |
                BRANCH=${{ env.BRANCH }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}